#!/bin/sh

# Use curl's --data-urlencode to URL-encode one or more arguments. See
# the curl manual for a full description of the syntax of this option
# (in short: prepend a = to any arg that isn't a key=value URL param).
# Encoded args will be separated by & in the output.

encode_arg() {
    curl -sw '%{url_effective}' --data-urlencode "$1" -G / | cut -c 3-
}

for i; do encode_arg "$i"; done | paste -s -d '&' -
