#!/bin/sh

if [ $# = 3 ]; then
    request_token_url="$1"
    authorize_url="$2"
    access_token_url="$3"
else
    echo "usage: $0 REQUEST_TOKEN_URL AUTHORIZE_URL ACCESS_TOKEN_URL"
    exit 2
fi

consumer_tmp=$(mktemp -t curlicue_consumer.XXXXXX)
request_token_tmp=$(mktemp -t curlicue_request_token.XXXXXX)
access_token_tmp=$(mktemp -t curlicue_access_token.XXXXXX)

read -p 'Consumer key: ' key
read -p 'Consumer secret: ' secret
echo "oauth_consumer_key=$key&oauth_consumer_secret=$secret" > $consumer_tmp

curlicue -f $consumer_tmp -p 'oauth_callback=oob' -- \
    -s -d '' "$request_token_url" > $request_token_tmp

echo -n 'Load this URL: '
curlicue -f $request_token_tmp -e "$authorize_url?oauth_token=\$oauth_token"
read -p 'Paste the PIN you got here: ' pin

curlicue -f $consumer_tmp -f $request_token_tmp -p "oauth_verifier=$pin" -- \
    -s -d '' "$access_token_url" > $access_token_tmp

read -p 'Output to file: ' output
paste -d '&' $consumer_tmp $access_token_tmp > "$output"

echo "OK! Now you can run: curlicue -f $output [-- CURL_OPTS] URL"
