#!/bin/sh

curlicue_key='UEMyorEm6xCJc9jDxxCw'
key_exchange_url='http://dev.twitter.com/apps/key_exchange'

if [ $# = 1 ]; then
    output_file="$1"
else
    echo "usage: $0 OUTPUT_FILE"
    exit 2
fi

echo "Load this URL: $key_exchange_url?oauth_consumer_key=$curlicue_key"
read -p 'Paste the string you got here: ' credentials
echo "$credentials" > "$output_file"
echo "OK! Now you can run: curlicue -f $output_file [-- CURL_OPTS] URL"
